name: Check PyPI Wheels
on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'  # 2pm UTC == 9am EST
jobs:
  generate_python_matrix:
    runs-on: ubuntu-latest
    outputs:
      python_versions: ${{ steps.set-matrix.outputs.python_versions }}
    steps:
      - name: Checkout STUMPY
        uses: actions/checkout@v4
        with:
          repository: stumpy-dev/stumpy
      - name: Upgrade Pip, Install Minimum Requirements
        run: |
          python -m pip install --upgrade pip pandas lxml
        shell: bash
      - name: Generate Python versions
        id: set-matrix
        run: |
          MIN_PYTHON=$(python ./versions.py -mode min | grep python | awk '{print $2}')
          MAX_PYTHON=$(python ./versions.py -mode max | grep python | awk '{print $2}')
          echo "python_versions=$(python ./versions.py -mode range $MIN_PYTHON $MAX_PYTHON)" >> $GITHUB_OUTPUT
        shell: bash
  check_pypi_wheels:
    needs: generate_python_matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ${{ fromJSON(needs.generate_python_matrix.outputs.python_versions) }}
    steps:
      - name: Checkout STUMPY
        uses: actions/checkout@v4
        with:
          repository: stumpy-dev/stumpy
      - name: Set Up Pixi
        uses: prefix-dev/setup-pixi@0.94
        with:
          pixi-version: v0.62.2
      - name: Set Up Python
        run: pixi add python="${{ matrix.python-version }}"
        shell: bash
      - name: Display Python Version
        run: pixi run python -c "import sys; print(sys.version)"
        shell: bash
      - name: Show Full Numba Environment
        run: pixi run python -m numba -s
        shell: bash
      - name: Prevent STUMPY Source Installation
        run: sed -i.BAK '/^\[tool\.pixi\.activation/,+2d' pyproject.toml && rm -rf pyproject.toml.BAK
        shell: bash
      - name: Display PyProject.toml
        run: cat pyproject.toml
        shell: bash
      - name: Run Unit Tests
        run: pixi run tests
        shell: bash
