name: Check Python Version End of Life
on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'  # 2pm UTC == 9am EST
jobs:
  check_python_version_eol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ '3.12' }}
      - name: Upgrade Pip, Install Minimum Requirements
        run: |
          python -m pip install --upgrade pip pandas lxml
        shell: bash
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
        shell: bash
      - name: Checkout STUMPY
        uses: actions/checkout@v4
        with:
          repository: stumpy-dev/stumpy
      - name: Check Python Version End of Life
        run: |
          if [[ `python ./versions.py | grep python | grep Mismatch | wc -l` -gt "0" ]]; then
            echo "Bump minimum version due to Python end-of-life"
            exit 1
          fi
        shell: bash
